server:
  port: 9888

spring:
  application:
    name: agent-server

  ai:
    openai:
      api-key: {GROQ_API_KEY}
      base-url: https://api.groq.com/openai
      chat:
        options:
          model: openai/gpt-oss-20b
          temperature: 0.7

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka

# ðŸš« Disable AWS auto-discovery
cloud:
  aws:
    stack:
      auto: false
